import { ZipArchive } from "archiver";
import { Readable } from "node:stream";
import { prisma } from "@/lib/db";
import { getTemplate } from "@/templates/registry";
import { portfolioDataSchema } from "@/lib/schema/portfolio";
import { validateSlug } from "@/lib/slug";
import { buildHtmlDocument } from "@/lib/document";
import { getPortfolioUploadPath } from "@/lib/images";

export interface ExportZipResult {
  stream: ReadableStream<Uint8Array>;
  filename: string;
}

export function generateReadme(name: string): string {
  return `================================================================================
${name.toUpperCase()} - PORTFOLIO EXPORT
================================================================================

This package contains your self-contained, static portfolio website.
It requires no server runtime, database, or build tools to display.

--------------------------------------------------------------------------------
1. VIEWING LOCALLY
--------------------------------------------------------------------------------
Simply double-click "index.html" to open your portfolio in any modern web
browser (Chrome, Firefox, Safari, Edge). Everything loads locally from the
accompanying "styles.css" and "assets/" folder.

--------------------------------------------------------------------------------
2. FREE STATIC HOSTING DEPLOYMENT
--------------------------------------------------------------------------------

Option A: Netlify Drop (Fastest - 30 seconds)
1. Go to https://app.netlify.com/drop
2. Drag and drop this entire unzipped folder into the browser window.
3. Your site will instantly be live on a secure HTTPS URL.

Option B: GitHub Pages
1. Create a new GitHub repository.
2. Push all files in this unzipped folder into your repository (main or gh-pages).
3. In repository Settings > Pages, select Branch: main and save.
4. Your portfolio will be live at https://<your-username>.github.io/<repo-name>/

Option C: Vercel
1. Install Vercel CLI (npm i -g vercel) or use the Vercel Dashboard.
2. Run "vercel deploy" inside this unzipped directory, or connect your Git repo.
3. Select "Other" for project framework preset and deploy.

--------------------------------------------------------------------------------
3. FILE MANIFEST
--------------------------------------------------------------------------------
- index.html   : Standalone semantic HTML page with relative asset links
- styles.css   : Self-contained scoped stylesheet
- assets/      : Images referenced by your portfolio
- README.txt   : Hosting and setup instructions

Generated by Portfolio Builder.
`;
}

/**
 * Builds a streamed ZIP archive for a published portfolio.
 * Contains index.html, styles.css, README.txt, and assets/<filename>.webp.
 * Returns null if slug is invalid, portfolio is missing, or data is corrupt.
 */
export async function buildPortfolioZip(slug: string): Promise<ExportZipResult | null> {
  const validation = validateSlug(slug);
  if (!validation.valid) {
    return null;
  }

  const record = await prisma.portfolio.findUnique({
    where: { slug },
  });

  if (!record) {
    return null;
  }

  const template = getTemplate(record.templateId);
  if (!template) {
    return null;
  }

  let rawData: unknown;
  try {
    rawData = JSON.parse(record.data);
  } catch {
    return null;
  }

  const parseResult = portfolioDataSchema.safeParse(rawData);
  if (!parseResult.success) {
    return null;
  }

  const data = parseResult.data;
  const fullName = data.basics.fullName || "Portfolio";

  // Build standalone static HTML document with relative assets and stylesheet
  const html = buildHtmlDocument(template, data, {
    assetBase: "./assets",
    title: fullName,
    externalStylesheet: "./styles.css",
  });

  const readme = generateReadme(fullName);

  // Setup archiver stream
  const archive = new ZipArchive({ zlib: { level: 9 } });
  const webStream = Readable.toWeb(archive) as ReadableStream<Uint8Array>;

  // Append static site root entries
  archive.append(html, { name: "index.html" });
  archive.append(template.css, { name: "styles.css" });
  archive.append(readme, { name: "README.txt" });

  // Gather referenced images and assets
  const referencedImages: string[] = [];
  if (data.basics.photo) {
    referencedImages.push(data.basics.photo);
  }
  if (data.contact.resumePdf) {
    referencedImages.push(data.contact.resumePdf);
  }
  for (const project of data.projects) {
    if (project.image) {
      referencedImages.push(project.image);
    }
  }

  const uniqueImages = Array.from(new Set(referencedImages));
  for (const img of uniqueImages) {
    const filePath = await getPortfolioUploadPath(record.id, img);
    if (filePath) {
      archive.file(filePath, { name: `assets/${img}` });
    }
  }

  // Finalize archive; finalize returns a Promise
  archive.finalize().catch((err: unknown) => {
    archive.destroy(err instanceof Error ? err : new Error(String(err)));
  });

  return {
    stream: webStream,
    filename: `${slug}-portfolio.zip`,
  };
}

/**
 * Convenience helper for tests and verification to collect the ZIP stream into a Buffer.
 */
export async function buildPortfolioZipBuffer(slug: string): Promise<{
  buffer: Buffer;
  filename: string;
} | null> {
  const res = await buildPortfolioZip(slug);
  if (!res) return null;

  const reader = res.stream.getReader();
  const chunks: Uint8Array[] = [];
  while (true) {
    const { done, value } = await reader.read();
    if (done) break;
    if (value) chunks.push(value);
  }
  return {
    buffer: Buffer.concat(chunks),
    filename: res.filename,
  };
}
